### ISSUE TITLE
Support for "Dvorak - Qwerty Cmd" Keyboard Layout

### ISSUE THREAD

**Issue by es2mac** [onevcat/VVDocumenter-Xcode#115]
Dvorak - Qwerty Cmd is my preferred keyboard layout.  Since its layoutID contains "Dvorak," when I type /// the "Cmd period" command is sent instead of the usual "Cmd V".  In this case Cmd-V is what should be sent.

If you could, please add a test for this special case.  Many thanks!

**Comment by onevcat** [comment]
Hi, @es2mac 
I am not a Dvorak user so I am not familiar with it. The Dvorak part of VVDocumenter is written by another contributor and it seems the Dvorak layout V is mapped to the period key in a standard keyboard. So I guess it is the correct logic to send Cmd-. instead of Cmd-V in a Dvorak layout? Is that right?

**Comment by es2mac** [comment]
That is correct for the normal Dvorak layout, but there's more than one Dvorak.  It's a bit confusing, but the one I use is called "Dvorak - Qwerty ⌘" and what it does is that when you are typing normally, it's the Dvorak layout, but when ⌘ key is down for a keyboard shortcut, it reverts back to Qwerty.  That means Cmd-V is still Cmd-V for "Dvorak - Qwerty ⌘."

![screen shot 2015-06-17 at 11 03 21 pm](https://cloud.githubusercontent.com/assets/6357130/8210541/15531c26-1545-11e5-9be8-1ef6d7ec5b6a.png)

**Comment by onevcat** [comment]
Wow..Didn't know about it. I will have a look at it to see what I can do for it.

**Comment by onevcat** [comment]
Should be fixed in #127

**Comment by es2mac** [comment]
Many thanks!
