### ISSUE TITLE
add modification info when editing file done

### ISSUE THREAD

**Issue by fealonelei** [onevcat/VVDocumenter-Xcode#215]
VVDocumenter is GREAT !!  
Could we have a new feature for collaboration ?    
As we know, Xcode will automatic create file header such as:
```
//
//  EducationView.m
//  
//
//  Created by Alice on 15/12/2.
//  Copyright © 2015 XX. All rights reserved.
```

Could we have a feature which can monitor the file is modified or not ? If someone modifies the file and done,  Add one line such as ` last modify by Bob on 16/04/05 ` , So we can easily find the author to discuss issues on the file .

```
//
//  EducationView.m
//  
//
//  Created by Alice on 15/12/2.
//  Last modify by Bob on 16/04/05 
//  Copyright © 2015 XX. All rights reserved.
```

I think this is a lot helpful. And add one more option on VV setting panel which allows someone add some personal info to help others to determine the modifier ?

**Comment by onevcat** [comment]
Hi, @fealonelei 

It is more likely a task of version control system than VVDocumenter. You can always use commands in [this page](http://stackoverflow.com/questions/278192/view-the-change-history-of-a-file-using-git-versioning) to see the modification history of a file. With a VCS, every time some code is checked in there could be a history log so you can always know who and when changed it. 

I believe it could be more reasonable to do it in that way, instead of through a plugin like VVDocumenter (which might not be installed by your collaborator).

How do you think about it?

**Comment by fealonelei** [comment]
Wow, sound GREAT !!  
谢喵神，我脑子瓦特了。。。。  
Have a great day !
